//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apteka063.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("apteka063.Resources.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active orders.
        /// </summary>
        internal static string ActiveOrders {
            get {
                return ResourceManager.GetString("ActiveOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available now:.
        /// </summary>
        internal static string AvailableNow {
            get {
                return ResourceManager.GetString("AvailableNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose order type.
        /// </summary>
        internal static string Choose_order_type {
            get {
                return ResourceManager.GetString("Choose_order_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to database update failed.
        /// </summary>
        internal static string DBUpdateFailed {
            get {
                return ResourceManager.GetString("DBUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to database update finished.
        /// </summary>
        internal static string DBUpdateFinished {
            get {
                return ResourceManager.GetString("DBUpdateFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined.
        /// </summary>
        internal static string Declined {
            get {
                return ResourceManager.GetString("Declined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency contacts.
        /// </summary>
        internal static string EmergencyContacts {
            get {
                return ResourceManager.GetString("EmergencyContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filling.
        /// </summary>
        internal static string Filling {
            get {
                return ResourceManager.GetString("Filling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        internal static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return back.
        /// </summary>
        internal static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the Main menu.
        /// </summary>
        internal static string GoToMenu {
            get {
                return ResourceManager.GetString("GoToMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been registered.
        /// </summary>
        internal static string HasBeenRegistered {
            get {
                return ResourceManager.GetString("HasBeenRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humanitarian Aid.
        /// </summary>
        internal static string Humaid {
            get {
                return ResourceManager.GetString("Humaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InProgress.
        /// </summary>
        internal static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main menu:.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need contact address.
        /// </summary>
        internal static string NeedAdress {
            get {
                return ResourceManager.GetString("NeedAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need contact name.
        /// </summary>
        internal static string NeedContactName {
            get {
                return ResourceManager.GetString("NeedContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need contact phone.
        /// </summary>
        internal static string NeedPhone {
            get {
                return ResourceManager.GetString("NeedPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New order.
        /// </summary>
        internal static string NewOrder {
            get {
                return ResourceManager.GetString("NewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No any active orders found.
        /// </summary>
        internal static string No_any_active_orders_found {
            get {
                return ResourceManager.GetString("No_any_active_orders_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented.
        /// </summary>
        internal static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is empty, please pick some.
        /// </summary>
        internal static string Order_is_empty_please_pick_some {
            get {
                return ResourceManager.GetString("Order_is_empty_please_pick_some", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order received, processing, please wait.
        /// </summary>
        internal static string Order_received_processing_please_wait {
            get {
                return ResourceManager.GetString("Order_received_processing_please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order №.
        /// </summary>
        internal static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm order reset:.
        /// </summary>
        internal static string OrderTypesConfirmOrderReset {
            get {
                return ResourceManager.GetString("OrderTypesConfirmOrderReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel order.
        /// </summary>
        internal static string OrderTypesWithResetOrder {
            get {
                return ResourceManager.GetString("OrderTypesWithResetOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick category:.
        /// </summary>
        internal static string PickCategory {
            get {
                return ResourceManager.GetString("PickCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pills.
        /// </summary>
        internal static string Pills {
            get {
                return ResourceManager.GetString("Pills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the address where order should be shipped.
        /// </summary>
        internal static string ProvideDeliveryAddress {
            get {
                return ResourceManager.GetString("ProvideDeliveryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the phone number of the person who will recieve the help.
        /// </summary>
        internal static string ProvidePhoneNumber {
            get {
                return ResourceManager.GetString("ProvidePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the contact name.
        /// </summary>
        internal static string ProvideReceiverName {
            get {
                return ResourceManager.GetString("ProvideReceiverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report suspicious activity.
        /// </summary>
        internal static string ReportActivity {
            get {
                return ResourceManager.GetString("ReportActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report incident.
        /// </summary>
        internal static string ReportIncident {
            get {
                return ResourceManager.GetString("ReportIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take care of yourself and loved ones.
        /// </summary>
        internal static string TakeCare {
            get {
                return ResourceManager.GetString("TakeCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport.
        /// </summary>
        internal static string Transport {
            get {
                return ResourceManager.GetString("Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have orders.
        /// </summary>
        internal static string You_dont_have_orders {
            get {
                return ResourceManager.GetString("You_dont_have_orders", resourceCulture);
            }
        }
    }
}
